### ISSUE TITLE
remove hardcoded texts

### ISSUE THREAD

**Issue by Njoguu** [Njoguu/Q-Lipa#3]

**Comment by Mutant-Slayer** [comment]
@Njoguu I am new to open source Can u pls assign this issue to me

**Comment by Njoguu** [comment]
hello @Mutant-Slayer, it has been a while since I've worked on this project, but sure, you can work on the issue

**Comment by Mutant-Slayer** [comment]
@Njoguu I have raised the PR. Please review and merge
